name: Build and Push Multi-arch Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build and push'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hasura/ndc-promptql-programs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        env:
          PP_VERSION: ${{ inputs.version }}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ inputs.version }} \
            --push \
            --annotation "index:org.opencontainers.image.description=NDC Connector to invoke PromptQL Programs (Automations)" \
            .